name: Publish Images

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
    branches:
      - master
      - backplane-2.9

jobs:
  build:
    env:
      context: "./"
      controlplane_image_name: "cluster-api-controlplane-provider-openshift-assisted"
      bootstrap_image_name: "cluster-api-bootstrap-provider-openshift-assisted"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Jinja2 CLI
        run: pip install jinja2-cli
      - name: Determine image tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          elif [[ $GITHUB_REF == refs/heads/master ]]; then
            TAG=latest
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            TAG=${BRANCH_NAME//\//-}
          fi
          echo "IMAGE_TAG=${TAG#v}" >> $GITHUB_ENV
          echo "Releasing ${TAG}"
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and publish bootstrap image to Quay
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ env.context }}
          tags: "${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ env.bootstrap_image_name }}:${{env.IMAGE_TAG}}"
          build-args: "PROVIDER=bootstrap"
      - name: Build and publish controplane image to Quay
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ env.context }}
          tags: "${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ env.controlplane_image_name }}:${{env.IMAGE_TAG}}"
          build-args: "PROVIDER=controlplane"
